// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:kairos/shared/models/hive/inspection_draft.dart';
import 'package:kairos/shared/models/hive/local_evidence.dart';
import 'package:kairos/shared/models/hive/sync_queue_item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(InspectionDraftAdapter());
    registerAdapter(LocalEvidenceAdapter());
    registerAdapter(SyncQueueItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(InspectionDraftAdapter());
    registerAdapter(LocalEvidenceAdapter());
    registerAdapter(SyncQueueItemAdapter());
  }
}
