import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../app/router.dart';
import '../app/theme/kairos_theme.dart';
import '../features/auth/data/auth_repository.dart';
import 'package:hive_ce_flutter/hive_flutter.dart';
import 'package:firebase_core/firebase_core.dart';
import '../core/services/push_notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  try {
    await Firebase.initializeApp();
    await PushNotificationService.instance.initialize();
  } catch (e) {
    debugPrint('Firebase initialization failed (might need flutterfire configure): $e');
  }

  // Initialize Hive
  await Hive.initFlutter();
  await Hive.openBox('sync_queue');

  // Register adapters (generated by hive_ce_generator)
  // Adapters will be registered here after running build_runner

  runApp(
    const ProviderScope(
      child: KairosApp(),
    ),
  );
}

class KairosApp extends ConsumerStatefulWidget {
  const KairosApp({super.key});

  @override
  ConsumerState<KairosApp> createState() => _KairosAppState();
}

class _KairosAppState extends ConsumerState<KairosApp> {
  @override
  void initState() {
    super.initState();
    // Restore session on startup
    Future.microtask(
      () => ref.read(authProvider.notifier).initialize(),
    );
  }

  @override
  Widget build(BuildContext context) {
    final router = ref.watch(routerProvider);

    return MaterialApp.router(
      title: 'KAIROS',
      theme: KairosTheme.lightTheme,
      routerConfig: router,
      debugShowCheckedModeBanner: false,
      builder: (context, child) {
        // Enforce minimum text scale for field readability
        return MediaQuery(
          data: MediaQuery.of(context).copyWith(
            textScaler: TextScaler.linear(
              MediaQuery.of(context).textScaler.scale(1.0).clamp(0.85, 1.3),
            ),
          ),
          child: child!,
        );
      },
    );
  }
}
